### PR TITLE
Installation manual for arch

### PR DESCRIPTION
**Pull request by etnbrd**

### CODE REVIEW

**Comment by clochix** [comment]
Hello @etnbrd,

Sorry, I didn't saw your last commits :-S

I don’t think we want an Arch official manual, because we won't be able to maintain it.

So, could you please submit a new PR with only your changes to the Debian documentation (If you don't want to rebase your updates, I'll do it myself).

**Comment by etnbrd** [comment]
Understandably.
I didn't linked it in the menu, so it should be kind of invisible, and we
(I) could provide it in the forum only when needed.

If you don't mind, I would like to keep it there (invisible) for
documentation, but if not, you can rebase my pull request :)

Thanks,

Etienne.

**Comment by clochix** [comment]
Thanks, I backported by hand most of your improvements ☺

Regarding the Arch Manual, I would prefer you put it on the forum, as a community contribution. Would you mind creating a new topic in https://forum.cozy.io/c/english/self-hosting ?

**Comment by etnbrd** [comment]
Done :)

You can remove it from the github repo.

**Pull request closed without merging**
