### PR TITLE
Feat.install debian

### PR DESCRIPTION
**Pull request by David-Guillot**

### CODE REVIEW

**Comment by David-Guillot** [comment]
@clochix i suggest commit-by-commit review on this one ;)

**Comment by David-Guillot** [comment]
@clochix please wait before reviewing this, i just found a much simpler solution :)

**Comment by David-Guillot** [comment]
@clochix this time this PR is ready to be reviewed ; the Apache / Let's Encrypt stuff was not trivial, but i have it working at home, so i decided to script it and share it in this docs.

**Comment by leolivier** [comment]
Hi @David-Guillot 
I'm facing a new problem on Apache proxying on cozy collect which, I think, needs to be documented:
I can't get it working and I have errors like this:
`time="2017-10-08T20:15:16+02:00" level=error msg="[http] GET /realtime/ websocket: not a websocket handshake: 'upgrade' token not found in 'Connection' header" domain=cozy.mytld
`
and also since 1.0.2 version of collect:
`time="2017-10-08T20:15:17+02:00" level=error msg="[http] GET /jobs/queue/konnector code=403, message=Forbidden" domain=cozy.mytld
`
(see issue https://github.com/cozy/cozy-collect/issues/303)

**Comment by clochix** [comment]
Hello,

We have published packages for Debian GNU/Linux and a tutorial on how to use them. The manual documentation is quite outdated and will probably be removed soon.

Sorry @David-Guillot, I didn't merge your proposal, as I wasn't sure it would make this documentation more clear.
Anyway, thanks a lot for your time and contribution 😍

**Comment by leolivier** [comment]
Hi @clochix
I saw you published packages for a simple installation and it's great for easing self hosting of cozy. However, Apache which is widly used in the world is still not addressed in the doc nor un the packages. Using nginx is not an option for me and I think I'm not the only one. This pr at least explained how to configure Apache reverse proxy, and missed the websocket part for collect...

**Pull request closed without merging**
